//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Warehouses = new HashSet<Warehouse>();
        }

        public int PurchaseId { get; set; }
        [DisplayName("Product Id")]
        public Nullable<int> ProductId { get; set; }
        [DisplayName("Supplier Id")]
        public Nullable<int> SupplierId { get; set; }
        [DisplayName("Store Id")]
        public Nullable<int> StoreId { get; set; }
        [DisplayName("Purchase Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> purchase_date { get; set; }
        [DisplayName("Unit Price")]
        public Nullable<decimal> unit_price { get; set; }
        [DisplayName("Quantity")]
        public Nullable<int> quantity { get; set; }
        [DisplayName("Total Price")]
        public Nullable<decimal> total_price { get; set; }
        [DisplayName("Vat")]
        public Nullable<decimal> vat { get; set; }
        [DisplayName("Grand Total Price")]
        public Nullable<decimal> grand_total_price { get; set; }
        [DisplayName("Stock Status")]
        public string stock_status { get; set; }
        [DisplayName("Memo No.")]
        public Nullable<int> memo_no { get; set; }
        [DisplayName("Comments")]
        public string comments { get; set; }

        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
