//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Stock
    {
        public int StockId { get; set; }
        [DisplayName("Product Id")]
        public Nullable<int> ProductId { get; set; }
        [DisplayName("Store Id")]
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Stutus { get; set; }

        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
